Message: Service ./chromedriver unexpectedly exited. Status code was: 127

Started
2021-08-11 12:48:13.990026
2021-08-11 13:48:17.755558
Traceback (most recent call last):
  File "main.py", line 25, in <module>
    scheduler4.run_pending()
  File "/home/priyanshu/.local/lib/python3.8/site-packages/schedule/__init__.py", line 100, in run_pending
    self._run_job(job)
  File "/home/priyanshu/.local/lib/python3.8/site-packages/schedule/__init__.py", line 172, in _run_job
    ret = job.run()
  File "/home/priyanshu/.local/lib/python3.8/site-packages/schedule/__init__.py", line 661, in run
    ret = self.job_func()
TypeError: sendAdmin() takes 0 positional arguments but 1 was given
Started
2021-08-11 15:01:14.389978
2021-08-11 16:01:18.231751
2021-08-11 17:01:21.970196
2021-08-11 18:01:25.561524
2021-08-11 19:01:29.228534
2021-08-11 20:01:33.124705
2021-08-11 21:01:37.017681
2021-08-11 22:01:40.832651
2021-08-11 23:01:44.621347
2021-08-12 00:01:48.473287
2021-08-12 01:01:52.288214
2021-08-12 02:01:56.285486
2021-08-12 03:02:00.125611
2021-08-12 04:02:04.029170
Traceback (most recent call last):
  File "main.py", line 24, in <module>
    scheduler3.run_pending()
  File "/home/priyanshu/.local/lib/python3.8/site-packages/schedule/__init__.py", line 100, in run_pending
    self._run_job(job)
  File "/home/priyanshu/.local/lib/python3.8/site-packages/schedule/__init__.py", line 172, in _run_job
    ret = job.run()
  File "/home/priyanshu/.local/lib/python3.8/site-packages/schedule/__init__.py", line 661, in run
    ret = self.job_func()
TypeError: sendAdmin() takes 0 positional arguments but 1 was given
Started
2021-08-14 16:42:16.655118
Traceback (most recent call last):
  File "main.py", line 26, in <module>
    time.sleep(1)
KeyboardInterrupt
